# Generated by Django 2.0.1 on 2018-02-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('adresse', models.TextField()),
                ('description', models.TextField()),
                ('a_hebergement', models.BooleanField()),
                ('a_soins', models.BooleanField()),
                ('a_biens_enssentiels', models.BooleanField()),
                ('a_banque_alimentaire', models.BooleanField()),
                ('a_assistance_psychologique', models.BooleanField()),
                ('a_aide_financiere', models.BooleanField()),
            ],
        ),
    ]
