# Generated by Django 2.0.1 on 2018-02-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ressource',
            old_name='description',
            new_name='description_fr',
        ),
        migrations.AddField(
            model_name='ressource',
            name='description_en',
            field=models.TextField(default='description_fr'),
            preserve_default=False,
        ),
    ]
