# Generated by Django 2.0.1 on 2018-02-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0003_auto_20180204_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressource',
            name='disponibilite',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='ressource',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='ressource',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
    ]
