# Generated by Django 2.0.1 on 2018-02-04 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0004_auto_20180204_0432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ressource',
            old_name='a_biens_essentiels',
            new_name='a_transport',
        ),
    ]
