# Generated by Django 2.0.1 on 2018-02-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.CharField(max_length=18)),
                ('horodatage', models.DateTimeField()),
                ('message_fr', models.TextField()),
                ('message_en', models.TextField()),
                ('type_message', models.CharField(choices=[('u', 'urgent'), ('n', 'normal'), ('i', 'info_general')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=18)),
                ('adresse', models.CharField(max_length=30)),
            ],
        ),
    ]
