# Generated by Django 2.0.1 on 2018-02-03 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Autorite',
        ),
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
