# Generated by Django 2.0.1 on 2018-02-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0004_batiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='titre_en',
            field=models.CharField(default='titre_en', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='titre_fr',
            field=models.CharField(default='titre_fr', max_length=20),
            preserve_default=False,
        ),
    ]
