# Generated by Django 2.0.1 on 2018-02-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0007_auto_20180204_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='citoyen',
            name='adresse',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='citoyen',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='citoyen',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=8),
        ),
    ]
